DROP TABLE WASAPPLICATIONS; 

CREATE TABLE WASAPPLICATIONS 
(
   ID	                  		bigint auto_increment not null primary key,
   STATUS	         		 	varchar(20) not null,
   CENTROCUSTO         			varchar(20) not null,
   DATATERMINO              	date,
   DATAPREVISTA              	date,
   OBSERVACAO              		varchar(1000),
   ACCESSOK			      		bool not null,
   RAMOOK		           		bool not null,
   OBSRAMO		           		varchar(1000),
   AVAILABLE					bool not null,
   ULTIMA_ATUALIZACAO   		date,
   USUARIO_ULTIMA_ATUALIZACAO   varchar(20),
   USUARIO_CRIACAO      		varchar(20),
   DATA_CRIACAO         		date
);

DROP TABLE FAQITEM; 

CREATE TABLE FAQITEM 
(
   ID	                  		bigint auto_increment not null primary key,
   DESCRIPTION         		 	text not null,
   TITLE	         			varchar(255) not null,
   ULTIMA_ATUALIZACAO   		date,
   USUARIO_ULTIMA_ATUALIZACAO   varchar(20),
   USUARIO_CRIACAO      		varchar(20),
   DATA_CRIACAO         		date
);

INSERT INTO FAQITEM (DESCRIPTION,TITLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('InitialContext ctx;
    ctx = new javax.naming.InitialContext();
    dataSource = (javax.sql.DataSource) ctx.lookup("jdbc/intranet_spbk_spbkd000_sql");
    conexao = dataSource.getConnection();
    this.conectado = true;','Exemplo de Conexão JDBC',CURDATE(), "brunojustino888", "brunojustino888", CURDATE());
    
INSERT INTO FAQITEM (DESCRIPTION,TITLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Deve utilizar os jars somente como referência para compilar do centro de custo LIBS/SENH/intranet_senh_corporativo_negocio_v2','Jar senh_usuario.jar',CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO FAQITEM (DESCRIPTION,TITLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('você pode realizar a alteração abaixo, acredito que o problema seja por conta do breadCrumb que foi implementado na aplicação.
O problema é que a aplicação utiliza o jar do (myfaces-all-1.1.1.jar a classe NavigationCase e NavigationRule) essas classes entram em conflito com jar de runtime do websphere do faces que é sempre carregado primeiro independente da ordem de carregamento de classe da aplicação. Para contornar esse problema foi alterada a classe que a aplicação utilizava conforme abaixo.
DE:
import org.apache.myfaces.config.element.NavigationRule;
import org.apache.myfaces.config.element.NavigationCase;
PARA:
import org.apache.myfaces.config.impl.digester.elements.NavigationCase;
import org.apache.myfaces.config.impl.digester.elements.NavigationRule;
Geralmente está na classe CrumbUtil.','Erro do Myfaces',CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

select * from FAQITEM;

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','afvd',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','agcp',CURDATE(),CURDATE(),'Aplicação migrada em 12/04/2018',true,true, true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','aneg',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bext',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bopc_web',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bopc_mdb',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bpvi',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','brfi_web',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bswi_web',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bswi_mdb',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bswp_web',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','bswp_mdb',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','btrm_mdb',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','btrm_web',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','capp',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','capp_v2',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','carg',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','cbpv',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','ccdc',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','cddo',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','chcs',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','chcs_tela_componente',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','cobc',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','dage',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','dica',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','efir',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','gfct',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','gptr',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','inec',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','inoc',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','legr',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','poup',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','pscl',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','rcop',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','rest',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','scoc',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','scon',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','scou',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','spbk',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','spbr',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

INSERT INTO WASAPPLICATIONS (STATUS,CENTROCUSTO,DATAPREVISTA,DATATERMINO,OBSERVACAO,ACCESSOK,RAMOOK,AVAILABLE,ULTIMA_ATUALIZACAO,USUARIO_ULTIMA_ATUALIZACAO,USUARIO_CRIACAO,DATA_CRIACAO) 
values ('Finalizado','tedb',CURDATE(),CURDATE(),'Fontes disponibilizados no Starteam',true,true,  true ,CURDATE(), "brunojustino888", "brunojustino888", CURDATE());

SELECT * FROM WASAPPLICATIONS;